AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/spec_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# standart: 10
Metrics/MethodLength:
  Max: 20
